apiVersion: v1
kind: Secret
metadata:
  name: {{ include "final-devops-chart.fullname" . }}-secret
  labels:
    {{- include "final-devops-chart.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secret.DATABASE_URL }}
  API_KEY: {{ .Values.secret.API_KEY }}
