apiVersion: v1
kind: Service
metadata:
  name: {{ include "final-devops-chart.fullname" . }}
  labels:
    {{- include "final-devops-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "final-devops-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
