apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-app-servicemonitor
  namespace: final-devops
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: devops-app
  endpoints:
  - port: http
    interval: 15s
    path: /metrics
