apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: final-devops-gitops-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/Ctrl-apk/devops-heros.git'
    targetRevision: HEAD
    path: final-devops-project/helm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: final-devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
