apiVersion: v1
kind: Secret
metadata:
  name: devops-app-secret
  namespace: final-devops
type: Opaque
data:
  # DATABASE_URL = postgresql://appuser:SecurePassword123!@postgres-db:5432/finaldb
  DATABASE_URL: cG9zdGdyZXNxbDovL2FwcHVzZXI6U2VjdXJlUGFzc3dvcmQxMjMhQHBvc3RncmVzLWRiOjU0MzIvZmluYWxkYg==
  # API_KEY = devops-secret-key-998877
  API_KEY: ZGV2b3BzLXNlY3JldC1rZXktOTk4ODc3
