apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-hero-gitops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Ctrl-apk/devops-heros.git'
    targetRevision: HEAD
    path: homework/19-monitoring-observability-gitops/app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
